### PR TITLE
Add ocenaudio

### PR DESCRIPTION
**Pull request by QORTEC**
ocenaudio is a simple, powerful, easy to use audio editor.

Site: https://www.ocenaudio.com/

### CODE REVIEW

**Comment by ikeydoherty** [comment]
Website says:

> All rights reserved Copyright© 2015

Is it still actively developed?

**Comment by QORTEC** [comment]
I believe that the **Ocenaudio Team** updated the website sometime around mid Q4 2015, and v3.1.5 was pushed out afterwards. 

In short, I'm not 100% sure but I think that its still "actively developed".

**Comment by QORTEC** [comment]
@ikeydoherty 
Updated pull request; Ocenaudio just updated to version 3.1.6

**Comment by ikeydoherty** [comment]
Thanks :)

**Pull request merged**
