### PR TITLE
Updated Software Version

### PR DESCRIPTION
**Pull request by Dgameman1**
I'm not sure what standard here is, but I updated the link to reflect the new version

### CODE REVIEW

**Comment by JoshStrobl** [comment]
You need to squash your commits and have a more descriptive commit message.

**Comment by Justinzobel** [comment]
Easiest way to ensure you make a single change is use common/Scripts/ep-update.py from the common git repo: https://git.solus-project.com/common

**Comment by JoshStrobl** [comment]
You really don't need to close PRs, just force for push a squashed commit to your branch...

**Comment by Dgameman1** [comment]
@JoshStrobl Sorry! I'm having a hell of a time trying to figure this out. Bear with me!

**Comment by Dgameman1** [comment]
Lmaoo oops

**Comment by DataDrake** [comment]
Sorry, I should have gotten to this sooner to save you the trouble. The ship a new version without the JDK which simplifies building the package and makes the initial download smaller:

https://github.com/solus-project/3rd-party/commit/b883c6ff184c7c58a729ae103297639c5a9c93b3

**Pull request closed without merging**
