### PR TITLE
Update pspec.xml

### PR DESCRIPTION
**Pull request by moriel5**
I realize that the 3rd party system already has both legs in the grave, however until it is completely superseded, the apps installed through it should receive updates.

### CODE REVIEW

**Comment by Justinzobel** [comment]
Updates haven't stopped, only new inclusions. In future please make the commit message long the lines of "Updated AnyDesk to 2.9.5" and include in the comments what was tested to ensure this update doesn't have any regressions.

**Comment by moriel5** [comment]
Thanks, I'll do so when I have the time, especially since I had made a .pspec of my own, based upon the official one (should be on my GitHub page, as I had forked it from here).

I am sorry about my misunderstanding, as I had thought that this system was over (aside from it functioning), since I am on the "unstable" branch.

Also, shouldn't ADB&Fastboot be officially packaged a .oepkg? My understanding of what ikey was told, is that they are properly open-sourced, and the one in the 3rd party repository is pretty outdated (I manually update them, however I think that they are important enough to receive automatic updates).

**Comment by Justinzobel** [comment]
It's likely in 3rd Party for a reason, likely licensing. If there are newer versions of it please feel free to create another pull request and we can look at merging it.

**Comment by moriel5** [comment]
Although I was under the impression that the license allows packaging ADB&Fastboot within the distro's native packaging system, but ikey said that it's a low priority issue, and that it'll eventually be properly packaged.

In any case, thanks for updating the AnyDesk .pspec so quickly.

**Pull request merged**
