### PR TITLE
Update Google Chrome Dev to 59.0.3071.9

### PR DESCRIPTION
**Pull request by EP01**

### CODE REVIEW

**Comment by sunnyflunk** [comment]
LGTM, thanks!

**Comment by sunnyflunk** [comment]
Note, please build the packages before submitting. This one failed without further changes

https://github.com/solus-project/3rd-party/commit/7410db53547c3b6ab3a92a516b84fa4211b98778

**Comment by EP01** [comment]
Sorry about that, will do. I was actually away from my Solus laptop when I submitted this, so just assumed there wasn't major changes. There's another update to 59.0.3071.15 available since Thursday if you want to do that?

**Comment by sunnyflunk** [comment]
Done

**Pull request merged**
