### PR TITLE
Changed vivaldi folder into vivaldi-beta and added vivaldi-snapshot f…

### PR DESCRIPTION
**Pull request by jholtiv**

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Please change vivaldi-beta back to vivaldi then I'll go ahead and test (keeps things consistent with the docs). If things check out I'll merge it in.

Thanks!

**Comment by jholtiv** [comment]
The reason I renamed it to vivaldi-beta is that in the original pspec.xml the name is <Name>vivaldi-beta</Name>

**Comment by ikeydoherty** [comment]
@jholtiv makes a good point about the name, I seen no harm in renaming it

**Comment by JoshStrobl** [comment]
Fair enough @ikeydoherty. @jholtiv I'll pull and review. Shouldn't take long :)

**Comment by JoshStrobl** [comment]
`vivaldi-snapshot` fails to build, invalid source:

```bash
sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/jholtiv/3rd-party/master/network/web/browser/vivaldi-snapshot/pspec.xml
Password: 
pspec.xml                      (1.0 KB)100%      9.80 MB/s [00:00:00] [complete]
actions.py                     (657.0  B)100%      6.01 MB/s [00:00:00] [complete]
DEBUG: InstallDB initialized in 0.0169751644135.
Building source package: vivaldi-snapshot
component.xml                  (52.0  B)100%    400.36 KB/s [00:00:00] [complete]
Fetching source from: https://vivaldi.com/download/download.php?f=vivaldi-snapshot_1.0.357.5-1_amd64.deb
download.php                   (122.0  B)  0%    882.88 KB/s [--:--:--]Source archive is stored: /var/cache/eopkg/archives/download.php
```

**Comment by jholtiv** [comment]
@JoshStrobl try now

**Comment by JoshStrobl** [comment]
Checked the spotify commit, please keep actions.py in for now.

vivaldi-snapshot issue:

``` bash
ActionsAPI [copy]: No file matched pattern "opt/vivaldi-beta/product_logo_16.png".
```

**Comment by JoshStrobl** [comment]
Might be worth actually testing the commits before doing PRs btw :P

**Comment by JoshStrobl** [comment]
@ikeydoherty Ya he fixed that in the "testing spotify" commit.

**Comment by ikeydoherty** [comment]
So at this point I'd like to see a fresh pull request.

Please ensure it's fully tested, also ensure you do not push .eopkg's.

When renaming a package, you must use the following stanza in your `pspec.xml`:

```xml

<Replaces>
    <Package>$oldpackage</Package>
</Replaces>
```

I look forward to reviewing the next pull request.

**Comment by jholtiv** [comment]
thanks guys, im learning. sorry

**Comment by ikeydoherty** [comment]
No need to apologise! It's just the way pull requests go.

You push, get your bit of feedback. If it needs changing, you make a fresh pull requests with the clean commits, and then we review and then hopefully merge :D

**Pull request closed without merging**
