### PR TITLE
Update Skype to version 8.17.76.3

### PR DESCRIPTION
**Pull request by Staudey**

### CODE REVIEW

**Comment by JoshStrobl** [comment]
LGTM. In the future, note that our [common repo](https://solus-project.com/articles/packaging/building-a-package/en/#setting-up-common) (just read the setting up common bit) has `Scripts/ep-update.py`, so you could just do `ep-update VERSION URL` (*I'd recommend making an alias*) and it'll update the pspec, add a history item, and update the sha. Saves you from editing mistakes.

**Comment by Staudey** [comment]
Oh, interesting. I haven't looked that much into it yet. Thanks for the tip!

**Comment by JoshStrobl** [comment]
No problem. I'll do a write-up on specifically updating Third Party repo items that we can reference it in the README in the future :)

**Comment by ahahn94** [comment]
Well, at least on my machine, updating the pspec.xml is not the time consuming part of the process 😁 
Nevertheless, good to know that there is a way to make our lives easier 😉

**Pull request merged**
