### PR TITLE
Updated TeamSpeak 3 Client name and description

### PR DESCRIPTION
**Pull request by CubeDev**

### CODE REVIEW

**Comment by JoshStrobl** [comment]
But...why? What's the issue with the current name of it. It's Teamspeak 3, it's obvious it's a client, no need for that.

**Comment by CubeDev** [comment]
It is a very small change. But it adds a comment, category and the correct name to the .desktop file.

**Comment by JoshStrobl** [comment]
But the name was already fine. We know it's a client, that doesn't need to be in the name. The keywords and categories bit I understand.

**Comment by CubeDev** [comment]
There is no problem with the commit, and it won't do any harm if it gets merged.

**Comment by JoshStrobl** [comment]
I stated on multiple occassion there isn't an issue with the name. I'll just fix this local.

**Pull request closed without merging**
