### PR TITLE
Update Unity to 5.6

### PR DESCRIPTION
**Pull request by theSoenke**

### CODE REVIEW

**Comment by Justinzobel** [comment]
This is a beta release, only update to stable releases.

**Comment by theSoenke** [comment]
@Justinzobel  The URL is a little confusing, but it's the final release of 5.6.0f3 https://forum.unity3d.com/threads/unity-on-linux-release-notes-and-known-issues.350256/

**Comment by DataDrake** [comment]
@Justinzobel All unity releases for linux are beta at the moment, otherwise they wouldn't be posting downloads on the forums. We made an exception for Unity. I just haven't had a chance to validate the PR yet.

**Comment by Justinzobel** [comment]
Ahh fair enough. Their urls suck indeed.

**Pull request closed without merging**
