### PR TITLE
Update GitKraken to 3.0

### PR DESCRIPTION
**Pull request by mattandersen**
New update and a small change to their deb file.

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Sorry, saw #210 first (maybe @miwilc should check before doing PRs first :P)

**Comment by mattandersen** [comment]
Womp womp! No worries.

**Comment by JoshStrobl** [comment]
@mattandersen I needed to reference your PR anyways, so all worked out in the end :P

**Comment by miwilc** [comment]
I forgot to check for the extensions/other PRs, I just edited this in the browser and assumed it would work.

Sorry :)

**Pull request closed without merging**
