### PR TITLE
Update the Jetbrains IDEs to the most recent versions

### PR DESCRIPTION
**Pull request by ahahn94**
- Update Rider to 2017.3.1
- Update RubyMine to 2017.3.2
- Update CLion, PyCharm & PyCharm-CE to 2017.3.3
- Update DataGrip, Idea, PhpStorm & WebStorm to 2017.3.4

Tests:
Build, Install, Execution

### CODE REVIEW

**Comment by ahahn94** [comment]
Please do me a favour and merge this soon while the updates are still fresh. :wink: 
Last PR(#286) was already outdated and still not merged.
I know you are all busy with the finishing touches for Solus 4, but please take the time to merge this, because only some of these are already available as snaps and the software center does not integrate snaps as of now.
Thanks in advance :grinning:

**Comment by davixcky** [comment]
How you find sha-1?

> Como encontraste el sha-1?

**Comment by DataDrake** [comment]
Sorry, I missed my notification for this. LGTM.

**Comment by ahahn94** [comment]
@davixcky Just download the file and use GtkHash to calculate the sha-256 and sha-1 sums. If the sha-256 sum in GtkHash matches the sha-256 sum on the website, the sha-1 is legit and can be used in the pspec.xml

**Comment by ahahn94** [comment]
@DataDrake No problem. Thanks 👍

**Comment by davixcky** [comment]
Thanks

**Comment by davixcky** [comment]
@ahahn94 Sorry, which file should I post? I don't now 
Pd: Google translate and me

**Comment by davixcky** [comment]
Which file? .sh . For example, in CLion is /bin/clion.sh ?

**Comment by ahahn94** [comment]
@davixcky 
To get the sha-1 sum of for example clion, go to the download page of clion (https://www.jetbrains.com/clion/download/download-thanks.html?platform=linux), wait for the download of the tar.gz-file to finish, and then use GTKHash to calculate both the sha-256 sum (for the verification of the file you just downloaded) and the sha-1 sum (which you need if you want to update the package to a newer version). You can then update the sha-1 sum and the update link in the pspec.xml-file and add a new Update-Entry in the history-part of the pspec.xml-file. Have a look at for example this commit e3d9928a41be6697f4b66603eb040fd0db531a17 to see the changes I made to the file while updating clion.

**Comment by ahahn94** [comment]
@davixcky But you do not need to worry about the jetbrains IDEs in this repo, I will have a look into them on a weekly basis and update every IDE that is outdated/has a newer version available.
This did not work out perfectly in the last weeks because of university, but it is much better now, so it should not be a problem.

**Comment by davixcky** [comment]
Goland ?

**Comment by ahahn94** [comment]
Goland will not be included in this repo as no new packages will be accepted.
You can install Goland using the Goland snap via 'snap install goland --classic' (prefered way, probably more up to date) or from my personal 3rd-party-repo https://github.com/ahahn94/my-3rd-party (probably outdated).

**Pull request merged**
