### PR TITLE
Update skype to 8.11.76.3

### PR DESCRIPTION
**Pull request by kyrios123**
Installed and launched -> OK. 

Signed-off-by: Pierre-Yves <pyu@riseup.net>

### CODE REVIEW

**Comment by Justinzobel** [comment]
Bit more testing would be great, login, test voice readback service, send a test message and confirm received?

**Comment by JoshStrobl** [comment]
Agreed with @Justinzobel. I've had Skype updates break audio input before, for example.

**Comment by kyrios123** [comment]
Called the echo sound test service.
Can't test message because I have no contacts... but my wife will yield at me soon enough if something doesn't work as she is the skype user.

**Comment by Justinzobel** [comment]
Add me, justin.zobel at the ol' gmail.com

**Comment by gromez** [comment]
I can confirm texting works fine, using this version since yesterday.

**Pull request merged**
