### PR TITLE
Update Plex Media Server to 1.3.3.3148

### PR DESCRIPTION
**Pull request by selwynorren**
Update Plex Media Server to 1.3.3.3148

### CODE REVIEW

**Comment by sunnyflunk** [comment]
This needs to be squashed into one commit as we need to keep the commit history clean.

Also it pays to build/install/test it prior to the PR to spot those little issues.

**Comment by selwynorren** [comment]
Hi there,

That's honestly my lack of knowledge showing regarding github. I am so sorry about that. When I made the edit, I copied the line wit the word history in it by accident, so it wrote it twice, so the second commit was just fixing that.

I dont know how to join them, should I delete my PR and redo?

**Comment by sunnyflunk** [comment]
Either that or it gives you the opportunity to learn how to use git to it's full potential! It was a struggle to begin with, but quite worthwhile

**Comment by selwynorren** [comment]
Seems I dont have the permission to squash, Ill delete and redo.

**Pull request closed without merging**
