### PR TITLE
add spideroak to network/download

### PR DESCRIPTION
**Pull request by murnux**
Add the spideroak syncing client and create download folder in network.

### CODE REVIEW

**Comment by JoshStrobl** [comment]
There any particular reason why `shutils' is being imported and the two lines that would've used it are commented out? Seems more sensible for those bits to just be removed entirely. Otherwise it looks good.

**Comment by murnux** [comment]
Ah yes, sorry aobut that. I went ahead and made those changes.

**Comment by JoshStrobl** [comment]
Good work :+1: Mind rebasing the commits and doing a force push so there is just a single commit for me to merge in? Otherwise it's a matter of me using GitHub's tool and that removes history.

**Comment by murnux** [comment]
Hmm, it turned the second commit into the complete one, but the first commit is still there. Idk if it's because I used the site for the initial pull. Any ideas on fixing that, or will that work?

**Comment by JoshStrobl** [comment]
You didn't rebase correctly. Basically your latest commit is just a renamed second commit. You need to rebase **both** commits: `git rebase -i HEAD~2` then `git push --force`

**Pull request closed without merging**
