### PR TITLE
Add PyCharm Community Edition

### PR DESCRIPTION
**Pull request by grski**
Unfortunately not everyone has professional edition purchased, so I added the free community edition by modifying the existing script for pycharm professional.
It doesn't confict with normaln pycharm - one can have both of them installed at the same time

### CODE REVIEW

**Comment by DataDrake** [comment]
I would probably have renamed this to pycharm-ce, but otherwise LGTM

**Comment by Justinzobel** [comment]
@grski see comments above re naming it.

**Comment by grski** [comment]
All done.

**Comment by m-delvalle** [comment]
@grski nice! would be a killer to do the same with IDEA :)

**Pull request merged**
