### PR TITLE
Updated Franz to 4.0.2

### PR DESCRIPTION
**Pull request by thecodechef**

### CODE REVIEW

**Comment by JoshStrobl** [comment]
Squash your commits into one please.

**Comment by thecodechef** [comment]
I would if i knew how im still quite new to this stuff

**Comment by JoshStrobl** [comment]
Follow the git rebase stuff [here](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) and do then force git push to rewrite your history.

**Comment by thecodechef** [comment]
I think that did it but im not sure though

**Pull request merged**
