### PR TITLE
update slack to 2.8.0

### PR DESCRIPTION
**Pull request by mcritchlow**
changelog: https://slack.com/release-notes/linux

key changes:

- All mentions of “team” have been changed to “workspace” when referring to the app, though not when referring to the people in it. You create a workspace. You invite people from your team. Simple!
- You can now configure the language used by the spellchecker in Preferences to be the language you wish to spell correctly.

### CODE REVIEW

**Comment by Justinzobel** [comment]
There's no history change, did you build this?

**Comment by mcritchlow** [comment]
Fixed, thanks for the catch @Justinzobel

**Comment by mcritchlow** [comment]
@ikeydoherty , I see this is repo is marked as deprecated now. Should I take that and the closing of this PR to mean that upgrade PR's won't be accepted anymore? Or, would you take a new PR based off the new repo/history?

**Comment by ikeydoherty** [comment]
Upgrades we'll take until we're all moved to Snaps, its new packages that are banned :)

**Pull request closed without merging**
