### PR TITLE
teamviewer 13

### PR DESCRIPTION
**Pull request by jvdneste**
These changes provide a working 64-bit teamviewer 13 (at least at the time I did them).
This is a beta release since tv13 is not officially released on linux yet.
However, a lot of people are looking for this since tv13 is standard on windows and tv12 won't connect to that.

It is perhaps preferred to keep tv12 as a separate package, in which case you should not pull my changes, but I just want to make my changes available.

### CODE REVIEW

**Comment by ahahn94** [comment]
The TeamViewer website does not mention the "beta" anymore, so it seems that the recent version (13.1.3026) is considered stable...

**Comment by ahahn94** [comment]
Hm, I installed version 13.1.8286 using your fork and the updated url and sha1... The TeamViewer UI still says "Preview"

**Comment by jvdneste** [comment]
I will probably retry these steps soon on a new machine.

**Comment by DataDrake** [comment]
They seem to still be marking this as preview on their website, but it's been a really long time that people have been stuck on 12 so I'd like to see this fixed. If you could update to the latest file, I'll get this merged.

**Comment by DataDrake** [comment]
No longer needed

**Pull request closed without merging**
