### PR TITLE
Update Spotify to 1.0.53.758

### PR DESCRIPTION
**Pull request by dylancl**

### CODE REVIEW

**Comment by ikeydoherty** [comment]
This is missing a bump to the History section

**Comment by dylancl** [comment]
Apologies, not that familiar with editing on github. Can I still change the history?

**Comment by ikeydoherty** [comment]
We have scripts for autobumping pspecs, like https://git.solus-project.com/common/tree/Scripts/pbump.py

You do have this cloned locally and checked out right? And have tested building the eopkg, etc?

**Comment by dylancl** [comment]
Ah, I see. Did not know about the script - again, apologies. 

I don't have it cloned locally, no. I don't plan on doing a lot of actual changes, just this one. 

I made a [issue report](https://github.com/solus-project/3rd-party/issues/150) for the issue which this fixes (or is supposed to fix) and tried doing it locally, but it seems that the software center does not read the local pspec.xml. 
I then figured that I should make a pull request since they all get checked and solve the issue that way.

This probably isn't the correct way of doing it, and if you can't accept the change I'm sorry.

**Comment by ikeydoherty** [comment]
Tell you what I'll help you out there :) Thx for the PR

**Pull request merged**
