### PR TITLE
adding vivaldi-beta & vivaldi-snapshot

### PR DESCRIPTION
**Pull request by jholtiv**
already tested

### CODE REVIEW

**Comment by JoshStrobl** [comment]
@jholtiv Please add the following to the `vivaldi-beta` pspec xml file inside the `<Package>` node, after Files:

``` bash
<Replaces>
    <Package>vivaldi</Package>
</Replaces>
```

This ensures that existing vivaldi users can upgrade to vivaldi-beta without file conflicts :)

**Comment by jholtiv** [comment]
@JoshStrobl thanks for the tip, hope we can merge this

**Comment by JoshStrobl** [comment]
@jholtiv Sorry for delay, I was sleeping :smile: . Reviewing now.

**Comment by JoshStrobl** [comment]
Merging. Thanks for your contributions :)

**Pull request merged**
