### PR TITLE
Add Franz

### PR DESCRIPTION
**Pull request by feskyde**
**Package:** `franz`.
**Description:** Franz is a free messaging app / former Emperor of Austria and combines chat & messaging services into one application.
**License:** Custom.

I also removed the "Operating System" from README to fit with the actual branding.

### CODE REVIEW

**Comment by JoshStrobl** [comment]
1. Have the README change as a separate PR please.
2. Do not remove headers from actions.py, indicating what the script was created for. Their existence is intentional.

**Comment by feskyde** [comment]
Done :smile:

**Comment by ikeydoherty** [comment]
There should be multiple Pull Requests here, and please ensure your commit messages make more sense than "Make it better", this is a repo that shares multiple source packages. Make *what* better? Why? How?

**Comment by feskyde** [comment]
Sorry @ikeydoherty :grin:

**Comment by ikeydoherty** [comment]
S'all good, happens :D

**Pull request merged**
