### PR TITLE
Edited pspec.xml to work with version 1.0.55.487

### PR DESCRIPTION
**Pull request by UnDim**

### CODE REVIEW

**Comment by UnDim** [comment]
Edited the pspec.xml to work with the new version of spotify

**Comment by JoshStrobl** [comment]
Was already fixed 9 hours ago but appreciate the patch.

**Comment by UnDim** [comment]
Did I do everything correctly?  This was my first pull request.
Thanks!

**Comment by JoshStrobl** [comment]
Yep, you did it correctly :+1:

**Pull request closed without merging**
