### PR TITLE
Add Skype for Linux Alpha

### PR DESCRIPTION
**Pull request by QORTEC**
Skype for Linux Alpha Info:
https://go.skype.com/linux.alpha/

Skype for Linux Alpha Repository:
https://repo.skype.com/latest/

### CODE REVIEW

**Comment by JoshStrobl** [comment]
A few issues:

1. You don't have an email specified in the pspec.xml
2. Maybe worth calling it skype, rather than skypeforlinux.
3. `<Dependency>binutils</Dependency>` needs to be added in the builddeps.

**Comment by JoshStrobl** [comment]
Err ignore email stuff.

**Comment by JoshStrobl** [comment]
:+1: Gonna test locally then merge in.

**Comment by QORTEC** [comment]
Thank you,
I'm off to G+ for Sundays with Solus

**Pull request merged**
